version: 2
updates:
  # Auto-update the Poetry package, but not tests
  - package-ecosystem: "pip"
    directory: "/pkgs"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
